[workspace]
members = [
    "call-home",
    "console-logger",
    "exporter",
    "k8s/plugin",
    "k8s/proxy",
    "k8s/supportability",
    "k8s/upgrade",
    "dependencies/control-plane/utils/dependencies/events-api",
]

exclude = [ "./dependencies/control-plane" ]
