apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-rest
  labels:
    app: api-rest
    helm-release: {{ .Release.Name }}
spec:
  type: {{ .Values.apis.rest.service.type }}
  selector:
    app: api-rest
  ports:
    - port: 8080
      name: https
      targetPort: 8080
      protocol: TCP
      {{- if eq .Values.apis.rest.service.type "NodePort" }}
      nodePort: {{ .Values.apis.rest.service.nodePorts.https }}
      {{- end }}
    - port: 8081
      name: http
      targetPort: 8081
      protocol: TCP
      {{- if eq .Values.apis.rest.service.type "NodePort" }}
      nodePort: {{ .Values.apis.rest.service.nodePorts.http }}
      {{- end }}
